  const pokemon=[
    {
        id:1,
        name:"Bulbizarre",
        image:"https://www.pokepedia.fr/images/4/4e/Miniature_001_LGPE.png"
    },
    {
        id:2,
        name:"Herbizarre",
        image:"https://www.pokepedia.fr/images/f/fb/Miniature_002_LGPE.png"
    },
    {
        id:3,
        name:"Florizarre",
        image:"https://www.pokepedia.fr/images/6/60/Miniature_003_LGPE.png"
    },
    {
        id:4,
        name:"Méga-Florizarre",
        image:"https://www.pokepedia.fr/images/a/a7/Miniature_003_Gigamax_EB.png"
    },
    {
        id:5,
        name:"Salamèche",
        image:"https://www.pokepedia.fr/images/8/89/Miniature_004_LGPE.png"
    },
    {
        id:6,
        name:"Reptincel",
        image:"https://www.pokepedia.fr/images/3/35/Miniature_005_LGPE.png"
    },
    {
        id:7,
        name:"Dracaufeu",
        image:"https://www.pokepedia.fr/images/6/68/Miniature_006_LGPE.png"
    },
    {
        id:8,
        name:"Dracaufeu",
        image:"https://www.pokepedia.fr/images/f/fb/Miniature_006_Gigamax_EB.png"
    },
    {
        id:9,
        name:"Méga-Dracaufeu X",
        image:"https://www.pokepedia.fr/images/9/99/Miniature_006_M%C3%A9ga_X.png"
    },
    {
        id:10,
        name:"Méga-Dracaufeu Y",
        image:"https://www.pokepedia.fr/images/d/db/Miniature_006_M%C3%A9ga_Y.png"
    },
    {
        id:11,
        name:"Carapuce",
        image:"https://www.pokepedia.fr/images/9/95/Miniature_007_LGPE.png"
    },
    {
        id:12,
        name:"Carabaffe",
        image:"https://www.pokepedia.fr/images/b/b6/Miniature_008_LGPE.png"
    },
    {
        id:13,
        name:"Tortank",
        image:"https://www.pokepedia.fr/images/7/73/Miniature_009_LGPE.png"
    },
    {
        id:14,
        name:"Tortank Gigamax",
        image:"https://www.pokepedia.fr/images/6/62/Miniature_009_Gigamax_EB.png"
    },
    {
        id:15,
        name:"Méga-Tortank",
        image:"https://www.pokepedia.fr/images/7/75/Miniature_009_M%C3%A9ga.png"
    },
    {
        id:16,
        name:"Chenipan",
        image:"https://www.pokepedia.fr/images/1/11/Miniature_010_LGPE.png"
    },
    {
        id:17,
        name:"Papilusion",
        image:"https://www.pokepedia.fr/images/5/5e/Miniature_012_EB.png"
    },
    {
        id:18,
        name:"Aspicot",
        image:"https://www.pokepedia.fr/images/c/cb/Miniature_013_LGPE.png"
    },
    {
        id:19,
        name:"Dardargnan",
        image:"https://www.pokepedia.fr/images/c/c9/Miniature_015_LGPE.png"
    },
    {
        id:20,
        name:"Roucarnage",
        image:"https://www.pokepedia.fr/images/b/b6/Miniature_018_LGPE.png"
    },
]
module.exports=pokemon;
